In [1]:
import pandas as pd
import numpy as np

In [2]:
from bs4 import BeautifulSoup

In [3]:
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
url

'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

In [4]:
import requests

In [5]:
page = requests.get(url)

In [6]:
import lxml.html as lh

In [7]:
doc = lh.fromstring(page.content)
tr_elements = doc.xpath('//tr')

In [8]:
[len(T) for T in tr_elements[:12]]

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

In [9]:
tr_elements = doc.xpath('//tr')
col=[]
i=0
for t in tr_elements[0]:
    i+=1
    name=t.text_content()
    col.append((name,[]))

In [10]:
#Since out first row is the header, data is stored on the second row onwards
for j in range(1,len(tr_elements)):
    #T is our j'th row
    T=tr_elements[j]
    
    #If row is not of size 3, the //tr data is not from our table 
    if len(T)!=3:
        break
    
    #i is the index of our column
    i=0
    
    #Iterate through each element of the row
    for t in T.iterchildren():
        data=t.text_content() 
        #Check if row is empty
        if i>0:
        #Convert any numerical value to integers
            try:
                data=int(data)
            except:
                pass
        #Append the data to the empty list of the i'th column
        col[i][1].append(data)
        #Increment i for the next column
        i+=1

In [11]:
Dict={title:column for (title,column) in col}
df=pd.DataFrame(Dict)

In [12]:
df.head(5)

  Postcode           Borough     Neighbourhood\n
0      M1A      Not assigned      Not assigned\n
1      M2A      Not assigned      Not assigned\n
2      M3A        North York         Parkwoods\n
3      M4A        North York  Victoria Village\n
4      M5A  Downtown Toronto      Harbourfront\n

In [13]:
df.dropna(axis = 0, how = 'all')

,Postcode,Borough,Neighbourhood
0,M1A,Not assigned,Not assigned\n
1,M2A,Not assigned,Not assigned\n
2,M3A,North York,Parkwoods\n
3,M4A,North York,Victoria Village\n
4,M5A,Downtown Toronto,Harbourfront\n
5,M5A,Downtown Toronto,Regent Park\n
6,M6A,North York,Lawrence Heights\n
7,M6A,North York,Lawrence Manor\n
8,M7A,Queen's Park,Not assigned\n
9,M8A,Not assigned,Not assigned\n
10,M9A,Etobicoke,Islington Avenue\n
11,M1B,Scarborough,Rouge\n
12,M1B,Scarborough,Malvern\n
13,M2B,Not assigned,Not assigned\n
14,M3B,North York,Don Mills North\n
15,M4B,East York,Woodbine Gardens\n
16,M4B,East York,Parkview Hill\n
17,M5B,Downtown Toronto,Ryerson\n
18,M5B,Downtown Toronto,Garden District\n
19,M6B,North York,Glencairn\n
20,M7B,Not assigned,Not assigned\n
21,M8B,Not assigned,Not assigned\n
22,M9B,Etobicoke,Cloverdale\n
23,M9B,Etobicoke,Islington\n
24,M9B,Etobicoke,Martin Grove\n
25,M9B,Etobicoke,Princess Gardens\n
26,M9B,Etobicoke,West Deane Park\n
27,M1C,Scarborough,Highland Creek\n
28,M1C,Scarborough,Rouge Hill\n
29,M1C,Scarborough,Port Union\n
...,...,...,...
258,M9X,Not assigned,Not assigned\n
259,M1Y,Not assigned,Not assigned\n
260,M2Y,Not assigned,Not assigned\n
261,M3Y,Not assigned,Not assigned\n
262,M4Y,Downtown Toronto,Church and Wellesley\n
263,M5Y,Not assigned,Not assigned\n
264,M6Y,Not assigned,Not assigned\n
265,M7Y,East Toronto,Business Reply Mail Processing Centre 969 East...
266,M8Y,Etobicoke,Humber Bay\n
267,M8Y,Etobicoke,King's Mill Park\n
268,M8Y,Etobicoke,Kingsway Park South East\n
269,M8Y,Etobicoke,Mimico NE\n
270,M8Y,Etobicoke,Old Mill South\n
271,M8Y,Etobicoke,The Queensway East\n
272,M8Y,Etobicoke,Royal York South East\n
273,M8Y,Etobicoke,Sunnylea\n
274,M9Y,Not assigned,Not assigned\n
275,M1Z,Not assigned,Not assigned\n
276,M2Z,Not assigned,Not assigned\n
277,M3Z,Not assigned,Not assigned\n
278,M4Z,Not assigned,Not assigned\n
279,M5Z,Not assigned,Not assigned\n
280,M6Z,Not assigned,Not assigned\n
281,M7Z,Not assigned,Not assigned\n
282,M8Z,Etobicoke,Kingsway Park South West\n
283,M8Z,Etobicoke,Mimico NW\n
284,M8Z,Etobicoke,The Queensway West\n
285,M8Z,Etobicoke,Royal York South West\n
286,M8Z,Etobicoke,South of Bloor\n
287,M9Z,Not assigned,Not assigned\n

In [14]:
df.columns

Index(['Postcode', 'Borough', 'Neighbourhood\n'], dtype='object')

In [15]:
df.rename(index=str, columns={'Neighbourhood\n': 'Neighbourhood'}, inplace = True)

In [16]:
df['Neighbourhood'] = df['Neighbourhood'].map(lambda x: x.rstrip('\n'))
df.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [17]:
df2 = df.where(df['Borough'] != 'Not assigned')

In [18]:
df2.dropna(axis = 0, how = 'all', inplace = True)
df2.head()

  Postcode           Borough     Neighbourhood
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M5A  Downtown Toronto       Regent Park
6      M6A        North York  Lawrence Heights

In [19]:
for i in range(len(df2)):
    if df2.iloc[i].Neighbourhood == 'Not assigned':
        df2.iloc[i].Neighbourhood = df2.iloc[i].Borough
df2.head(10)

   Postcode           Borough     Neighbourhood
2       M3A        North York         Parkwoods
3       M4A        North York  Victoria Village
4       M5A  Downtown Toronto      Harbourfront
5       M5A  Downtown Toronto       Regent Park
6       M6A        North York  Lawrence Heights
7       M6A        North York    Lawrence Manor
8       M7A      Queen's Park      Queen's Park
10      M9A         Etobicoke  Islington Avenue
11      M1B       Scarborough             Rouge
12      M1B       Scarborough           Malvern

In [20]:
df2.where(df2.Neighbourhood == 'Not assigned').count()

Postcode         0
Borough          0
Neighbourhood    0
dtype: int64

In [21]:
df3 = df2

In [22]:
for i in range(len(df3)):
    count = 0
    for j in range(len(df3)-1):
        if df3.iloc[i].Postcode == df3.iloc[j+1].Postcode:
            count = count + 1
        if count > 1:
            df3.iloc[i].Neighbourhood = df3.iloc[i].Neighbourhood+','+df3.iloc[j+1].Neighbourhood
df3.head(10)

,Postcode,Borough,Neighbourhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Harbourfront,Regent Park,Lawrence Heights,Lawr..."
5,M5A,Downtown Toronto,"Regent Park,Regent Park,Lawrence Heights,Lawre..."
6,M6A,North York,"Lawrence Heights,Lawrence Manor,Queen's Park,I..."
7,M6A,North York,"Lawrence Manor,Lawrence Manor,Queen's Park,Isl..."
8,M7A,Queen's Park,Queen's Park
10,M9A,Etobicoke,Islington Avenue
11,M1B,Scarborough,"Rouge,Malvern,Don Mills North,Woodbine Gardens..."
12,M1B,Scarborough,"Malvern,Malvern,Don Mills North,Woodbine Garde..."

In [23]:
df4 = df3

In [24]:
df4.head()

,Postcode,Borough,Neighbourhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Harbourfront,Regent Park,Lawrence Heights,Lawr..."
6,M6A,North York,"Lawrence Heights,Lawrence Manor,Queen's Park,I..."
8,M7A,Queen's Park,Queen's Park

In [25]:
df4.drop_duplicates(subset = ['Postcode'], keep = 'first', inplace = True)
df4.head(10)

,Postcode,Borough,Neighbourhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Harbourfront,Regent Park,Lawrence Heights,Lawr..."
6,M6A,North York,"Lawrence Heights,Lawrence Manor,Queen's Park,I..."
8,M7A,Queen's Park,Queen's Park
10,M9A,Etobicoke,Islington Avenue
11,M1B,Scarborough,"Rouge,Malvern,Don Mills North,Woodbine Gardens..."
14,M3B,North York,Don Mills North
15,M4B,East York,"Woodbine Gardens,Parkview Hill,Ryerson,Garden ..."
17,M5B,Downtown Toronto,"Ryerson,Garden District,Glencairn,Cloverdale,I..."